---

# Install PHP extensions
- name: "Install PHP extensions"
  ansible.builtin.apt:
    state: present
    name: "php{{ php_version }}-{{ item }}"
    update_cache: true
  become: true
  loop: "{{ php_extensions }}"

# Install Composer system-wide
- name: "Install global Composer"
  ansible.builtin.get_url:
    url: "https://getcomposer.org/download/{{ composer_version }}/composer.phar"
    dest: "{{ composer_path }}"
    mode: "0775"
  become: true
