$ANSIBLE_VAULT;1.1;AES256
38393338626232323336653662343566396230386365316539333931633432653132306561376532
6139363763313931663536336134363034666266653738370a366563393562613037613938646133
66383062366231323864393564343065303163613863613830353334313433343663643233636366
3863313562393731660a333061323362386638346430393333386633393533343434353832353764
34653333393939316564313766376139666431643361666534376164643833333963656566393164
31646666623962383761303439666661643031343532663434646337663830656661323763626130
36636466336261626234363464623437616238383032316131363763633164323331326439396435
66376437303130643364623063616638366638323232346166376437623734323837313937616466
3965
