$ANSIBLE_VAULT;1.1;AES256
36653034343734623333323261626462653663373034653164666538346564663034613163303634
3332323961323537313064386633373661326365613165320a626533613333316532363362616633
63366137393131326333633161636465303338373538613261636537373937346463393938663661
6239316437303166320a653235653630303136393639376330363364393162366362343962383166
31393630643064613536616230643164633530323265383034376337373261303139376265633839
30336439366631333838623463313835313464646465616433343866646265643163323430663365
64613864373532323439336564386465653134386462386235616562663831633463633034323162
33393639323633303462373339303633386366333130393438643864656464333034656665636237
64393133326538376232666539653864346562336431383139666163353332306662663462313535
35383666623831636666643337323363373131326461353431643161353431616266363433356639
393736333237643036353336623062633934
