$ANSIBLE_VAULT;1.1;AES256
63356439633835383038373738623634336266343833383537316634663732326136616564383338
3362353563636664386664393361643064646630363162330a383663353731626336326438623638
39623435626539616139393137643131623934306130363362383162356431633338396134636164
3965376531333839610a636531396166313631323135343563633935646564643965376163343736
61633933646139383831636363376665633432396335373435386338303537383762336634633632
65333636386139623638616361316363303038376161636261623263383061373165313661316233
39323038393561653633376337613965653232656639666162313837616563303264396631323735
65613634613434363035323732386631383033363561353732643738363964353936313634356238
34343734633866336565363336653536316132363564316364636332386631653733616539663665
39366139663063633334326363303435636533663935386436313434323238363334373164363332
663637363264656266653765393733313632
