# Secrets in inventory/prod/group_vars/clientMH/vault.yml
  
ansible_host: "{{ vault_mh_host04.ip }}"
ansible_port: "{{ vault_mh_host04.port }}"
fqdn: "{{ vault_mh_host04.fqdn }}"
hardware: "{{ vault_mh_host04.hardware }}"
cloudflare_enabled: 
vscode_enabled: true
host_secured: true

# host-specific SSH users
ssh_users:
  - "{{ vault_mh_host04.ssh_users.dev | default('') }}"
  - "{{ vault_mh_host04.ssh_users.os  | default('') }}"

# Client info
env: prod               # environment for playbooks
client_name: clientMH   # client name for playbooks

# LAMP stack
stack:
  os: ubuntu-24
  php: php-83
  mysql: mysql-80
  apache: apache-24
  drupal: drupal11.3

# override Composer version
composer_version: "2.8.12"

# Supported platforms for this host
platforms:
  drupal11.2:
    user: drupal11_2
    group: drupal11_2
  drupal11.3:
    user: drupal11_3
    group: drupal11_3
  crm-2508:
    user: crm
    group: crm
  crm-2601:
    user: crm
    group: crm

# Catch-all Apache/SSL settings for this host
# CF is defined for the fqdn apex domain only.
apache_catch_all_cf:
  zone_id: "{{ vault_mh_host04.catchall.cf.zone_id | default('dummy') }}"
  api_key: "{{ vault_mh_host04.catchall.cf.api_key | default('') }}"
apache_catch_all_ssl:
  provider: cloudflare
  renewal_days: 365   # choose your window
  force_renew: false
