$ANSIBLE_VAULT;1.1;AES256
30663139626535623266386533363664306464393333373239653139363736646337386232663032
3834393762653365373437393834353462353665636430640a623865353262386264303663303137
33393730323961373936663233643066336235613734363262356163346366313963333133343334
6139313462356565390a353065396535613934373666303939643730326362383835646133323663
38333638343137623038386539653164323765623432613431386336613530646139333462633666
38386432313665333534346533366661633432646233373932663364613962366139383166636335
66336439376234656665323062353838353061383361393638646138316231613838656435636261
35353965643963643238633966303564613461643432363534313265373961643833333736376237
62346162343133633035376566313438396237393463396265303535346264616431646364343662
37613339363238646536613134643537626134323039343839313833356364356461393262343339
34656563396130396665313332366464323163303665663561343066616462343234646663323431
31333165626639626538306631623930636338636236376666323636313562633963323433663538
3037
