$ANSIBLE_VAULT;1.1;AES256
62366334383931656138343865316331326664366564363039656263653239373965376131343837
3863633862653262663861306537376230376466383734620a383161663231613735383662333239
37626333383435626334663037366339306264323837353764336462323937363836323463333434
3539313136386365640a656239313635396133656266326664666333343430616461336330656461
34643661313234663337316537633534336263663935383764313038313139303035613931666631
65306236356435303135346334333866656361333930613439653236316534336139303232326436
37663831353839336264343135326331376565323430343639303631393966663465633335616637
30663166613236623239316632393166653962623131626261323339303136346165383931343336
62353739383937396166613064353938643533326566623837366533346266356465336339333133
61336363653061613966636231343263326630333235313436333338663230636430383364363061
61376462326664643237633764353663313664303330356436373530343461326238303933303035
34313266306233313866323138306235336266386336666332373330326138633939633566643763
31363464623464646432353039396133356137313133346539356536366633643265
