$ANSIBLE_VAULT;1.1;AES256
30353837323262316137343761643438373533646462383636663636663366356536356133666363
3162643834393930643630383061303933646239303332660a373065623962383338326535643635
63646165303131303366636166386137393961343835343730326665383761376432383431313166
6334383161346363360a366232646433383635376265623637303233396335373033373461663133
36353536323533656662323839316562373535353963653436383363363436633138326138623031
32643335336638303633386435653262613039376362313361383234383535616666663134613433
61393361393765386462313662363062326439633431316630623466373762646636353439343132
31313666613336383933613338646436393230626361393763636465303838363764323631666231
35636531343739376531366430386464643335323663323436313637386364613535376237343937
30363834323538656233306362323666646362313939343232636663313938396436656231353634
30653538643234396565643235656463663333626532616537643165613838383764336331393330
66643133306530666166
