# Prepares platform prerequisites and installs Drupal codebases via Composer.

- name: Install Drupal platform
  ansible.builtin.include_tasks:
    file: install-drupal-platform.yml
  vars:
    platform_item: "{{ platform_selected }}"
  when:
    - platform_selected is defined
    - (platform_selected.value.state | default('present')) != 'absent'
