---
ansible_host: mh-host03-prod
platforms:
  - name: "d11_standard"
    path: "/var/www/platforms/d11_standard"
    composer_project: "argopecten/drupal-project:d11"
    state: present

sites:
  - name: "client1-main"
    fqdn: "www.client1.com"
    platform: "d11_standard"
    db_name: "client1_main"
    db_user: "client1_main"
    db_password: "{{ vault_client1_main_db_password }}"
    admin_user: "admin"
    admin_pass: "{{ vault_client1_admin_pass }}"
    state: present
