---
# Removes Drupal platforms that are explicitly managed (state != absent).

- name: Remove retired Drupal platform
  ansible.builtin.include_tasks:
    file: remove.yml
  vars:
    platform_item: "{{ platform_selected }}"
  when:
    - platform_selected is defined
    - (platform_selected.value.state | default('present')) != 'absent'
