---
# Updates Drupal platforms via Composer.

- name: Update Drupal platform
  ansible.builtin.include_tasks:
    file: update.yml
  vars:
    platform_item: "{{ platform_selected }}"
  when:
    - platform_selected is defined
    - (platform_selected.value.state | default('present')) != 'absent'
