---
# Variables for client sites

client: "clientA"

sites:
  civilcrm_hu:
    name: "civilcrm.hu"
    server: r04
    platform: drupal11min
    modules: []
    # from vault file, encrypted with ansible-vault
    cf:
      zone_id: "{{ civilcrm.zone_id | default('dummy') }}"
      email: "{{ civilcrm.email | default('dummy') }}"
      api_key: "{{ civilcrm.api_key | default('dummy') }}"
      private_key: "{{ civilcrm.key | default('dummy') }}"

  c1_civilcrm_hu:
    name: "c1.civilcrm.hu"
    server: r04
    platform: drupal11min
    modules: []
    # from vault file, encrypted with ansible-vault
    cf:
      zone_id: "{{ civilcrm.zone_id | default('dummy') }}"
      email: "{{ civilcrm.email | default('dummy') }}"
      api_key: "{{ civilcrm.api_key | default('dummy') }}"
      private_key: "{{ civilcrm.key | default('dummy') }}"

  c2_civilcrm_hu:
    name: "c2.civilcrm.hu"
    server: r04
    platform: drupal11min
    modules: []
    # from vault file, encrypted with ansible-vault
    cf:
      zone_id: "{{ civilcrm.zone_id | default('dummy') }}"
      email: "{{ civilcrm.email | default('dummy') }}"
      api_key: "{{ civilcrm.api_key | default('dummy') }}"
      private_key: "{{ civilcrm.key | default('dummy') }}"

  c3_civilcrm_hu:
    name: "c3.civilcrm.hu"
    server: r04
    platform: drupal11min
    modules: []
    # from vault file, encrypted with ansible-vault
    cf:
      zone_id: "{{ civilcrm.zone_id | default('dummy') }}"
      email: "{{ civilcrm.email | default('dummy') }}"
      api_key: "{{ civilcrm.api_key | default('dummy') }}"
      private_key: "{{ civilcrm.key | default('dummy') }}"
