---
# Variables for Nginx webservers

#############
# Drupal platforms on the webservers
platforms:
  drupal10:
    version: "10.4.0"
    profile: "standard"
    path: "/var/www/"
    name: "drupal10"
    user: "d10user"
    group: "d10user"
    # Composer Requirements
    dependencies:
      - "drush/drush:^13.3"
      - "drupal/admin_toolbar:^3.0"
      - "drupal/pathauto:^1.8"
  drupal11:
    version: "11.1"
    profile: "standard"
    path: "/var/www/"
    name: "drupal11"
    user: "d11user"
    group: "d11user"
    # Composer Requirements
    dependencies:
      - "drush/drush:^13.3"
  drupal11min:
    version: "11.1"
    profile: "minimal"
    path: "/var/www/"
    name: "drupal11min"
    user: "d11user"      # should be d11minuser
    group: "d11user"
    # Composer Requirements
    dependencies:
      - "drush/drush:^13.3"

# Drush Configuration
drush_path_site: "{{ drupal_path}}/vendor/bin/drush"

# Additional arguments for the site-install command
drupal_site_install_extra_args: []

# Drupal repository
# TBC drupal_repo: "https://git.drupalcode.org/project/drupal"
composer_project_options: "--prefer-dist --stability dev --no-interaction"

# Permissions for the Drupal directory
drupal_root_permissions: "0750"
#####################

### Variables for composer
# Global (system-wide) Composer
composer_version: "2.8.4" 
composer_path: "/usr/bin/composer"


###  Variables for the PHP role
php_version: "8.3"                # Define the PHP version to be used

# PHP Compatibility Matrix
php_extensions: [fpm, curl, gd, mbstring, mysql, xml, zip, bcmath, intl, soap]

# Define the PHP repositories
php_repositories:
  - { repo: 'ppa:ondrej/php' }      # the main PHP repository
  - { repo: 'ppa:ondrej/nginx' }    # the Nginx repository


# Define the PHP configuration file path
php_ini_path: "/etc/php/{{ php_version }}/fpm/php.ini" # Define default PHP configuration settings

# Define the list of PHP configuration changes using variables
php_date_timezone:             "Europe/Budapest"  # Set the default timezone for PHP
php_max_execution_time:        240           # Set the maximum execution time for PHP scripts (in seconds)
php_max_input_time:            120               # Set the maximum input time for PHP scripts (in seconds)
php_post_max_size:             "50M"              # Set the maximum size of POST data that PHP will accept
php_upload_max_filesize:       "50M"        # Set the maximum size of uploaded files that PHP will accept

# Define the list of PHP configuration changes using variables
php_configurations:
  - { regexp: '^;date.timezone =', line: 'date.timezone = {{ php_date_timezone }}' }
  - { regexp: '^max_execution_time =', line: 'max_execution_time = {{ php_max_execution_time }}' }
  - { regexp: '^max_input_time =', line: 'max_input_time = {{ php_max_input_time }}' }
  - { regexp: '^post_max_size =', line: 'post_max_size = {{ php_post_max_size }}' }
  - { regexp: '^upload_max_filesize =', line: 'upload_max_filesize = {{ php_upload_max_filesize }}' }


###  Variables for the Nginx webserver
# Apt packages to install
nginx_packages:
  - nginx

# OS-specific variables for Nginx
nginx_main_conf_file: /etc/nginx/nginx.conf       # main configuration file
nginx_conf_path: /etc/nginx/conf.d                # configuration directory
nginx_snippets_path: /etc/nginx/snippets          # snippets directory
nginx_vhost_path: /etc/nginx/sites-enabled

nginx_deny_files:
  - .htpasswd
  - .htaccess
  - .git
  - .env
  - .DS_Store

### Variables used within the main nginx's context

# Listen on IPv6 (default: true)
# TBD: nginx_listen_ipv6: true

# Nginx basic options
nginx_user: "www-data"
nginx_group: "www-data"
nginx_worker_processes: >-
  "{{ ansible_processor_vcpus | default(ansible_processor_count) }}"
nginx_pidfile: /run/nginx.pid

# Extra main options
nginx_extra_conf_options: |
  include           /etc/nginx/modules-enabled/*.conf;

# Events options
nginx_worker_connections: "1024"
nginx_multi_accept: "off"

# HTTP options
nginx_sendfile: "on"                     # enable transfer static files directly from disk
nginx_tcp_nopush: "on"                   # sending out partial packets in one go
nginx_tcp_nodelay: "on"                  # enable TCP_NODELAY: packets are sent immediately
nginx_types_hash_max_size: 2048          # maximum size of the hash table for types
nginx_keepalive_timeout: 75              # keep-alive timeout in seconds
nginx_keepalive_requests: 600            # maximum number of keep-alive requests
nginx_server_tokens: "off"               # hide nginx version
nginx_server_names_hash_bucket_size: 64  # size of the hash bucket for server names
nginx_server_name_in_redirect: "off"     # disable server name in redirects
nginx_client_max_body_size: "64m"        # maximum allowed request body size in megabytes

# SSL options
nginx_ssl_protocols: "TLSv1.2 TLSv1.3"   # supported SSL protocols
nginx_ssl_prefer_server_ciphers: "on"    # prefer server ciphers over client ciphers
nginx_ssl_ciphers: >-                    # supported SSL ciphers from Cloudflare's primary recommendations
  ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:
  ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:
  ECDHE-ECDSA-CHACHA20-POLY1305:ECDHE-RSA-CHACHA20-POLY1305

# logging
nginx_access_log: "/var/log/nginx/access.log main buffer=16k flush=2m"
nginx_error_log: "/var/log/nginx/error.log warn"
nginx_log_format: |-
  '$remote_addr - $remote_user [$time_local] "$request" '
  '$status $body_bytes_sent "$http_referer" '
  '"$http_user_agent" "$http_x_forwarded_for"'
nginx_log_format_aegir: |-
  '"$proxy_add_x_forwarded_for" $host [$time_local] '
  '"$request" $status $body_bytes_sent '
  '$request_length $bytes_sent "$http_referer" '
  '"$http_user_agent" $request_time "$gzip_ratio"'
nginx_log_format_json: |-
  '{ "time": "$time_iso8601", '
  '"remote_addr": "$remote_addr", '
  '"remote_user": "$remote_user", '
  '"request": "$request", '
  '"status": "$status", '
  '"body_bytes_sent": "$body_bytes_sent", '
  '"http_referer": "$http_referer", '
  '"http_user_agent": "$http_user_agent", '
  '"http_x_forwarded_for": "$http_x_forwarded_for" }'

# gzip options
nginx_gzip:              "on"       # enable gzip compression
nginx_gzip_static:       "on"       # serve pre-compressed files if they exist
nginx_gzip_vary:         "on"       # enable the "Vary: Accept-Encoding" header to responses
nginx_gzip_proxied:      "any"      # enable gzip for proxied requests
nginx_gzip_buffers:      "16 8k"    # number and size of buffers for gzip
nginx_gzip_comp_level:   8          # compression level (1-9)
nginx_gzip_http_version: 1.1        # minimum HTTP version to use gzip
nginx_gzip_min_length:   50         # minimum length of response to compress in bytes
nginx_gzip_types: >-                # MIME types to compress
  application/atom+xml
  application/javascript
  application/json
  application/rss+xml
  application/vnd.ms-fontobject
  application/x-font-opentype
  application/x-font-ttf
  application/x-javascript
  application/xhtml+xml
  application/xml
  application/xml+rss
  font/opentype
  image/svg+xml
  image/x-icon
  text/css
  text/javascript
  text/plain
  text/xml

nginx_extra_http_options: ""
# Example extra http options, printed inside the main server http config:
#    nginx_extra_http_options: |
#      proxy_buffering    off;
#      proxy_set_header   X-Real-IP $remote_addr;
#      proxy_set_header   X-Scheme $scheme;
#      proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
#      proxy_set_header   Host $http_host;

# includes
nginx_mime_file: /etc/nginx/mime.types
