---
# Restores Drupal platforms from archived backups.

- name: Restore Drupal platform
  ansible.builtin.include_tasks:
    file: restore.yml
  vars:
    platform_item: "{{ platform_selected }}"
  when:
    - platform_selected is defined
    - (platform_selected.value.state | default('present')) != 'absent'
