---
# defaults file for php
php_overrides_conf_filename: "99-ansible-overrides.ini"
php_cli_configurations: []
php_fpm_configurations: []
php_fpm_config_file: "/etc/php/{{ php_version }}/fpm/php-fpm.conf"
php_fpm_pool_config_file: "/etc/php/{{ php_version }}/fpm/pool.d/www.conf"
php_fpm_error_log: "/proc/self/fd/2"
php_fpm_log_level: "notice"
php_fpm_access_log: "/proc/self/fd/2"
php_fpm_catch_workers_output: "yes"
php_fpm_decorate_workers_output: "yes"
php_fpm_slowlog: "/proc/self/fd/2"
php_fpm_request_slowlog_timeout: "5s"
