---
sites:
  cd:
    host: "mh-host04"
    name: "{{ vault_mh_host04.cd.name }}"
    platform: "drupal11.2"
    profile: "standard"
    admin_user: "admin"
    civicrm_install: true
    modules_enable:
      - syslog
    modules_disable:
      - dblog
    cf:
      zone_id: "{{ vault_mh_host04.cd.cf.zone_id | default('dummy') }}"
      api_key: "{{ vault_mh_host04.cd.cf.api_key | default('dummy') }}"
    state: present
