######
# 
# This Ansible playbook removes Drupal platforms and related resources from
# webservers. It shares the same execution context as platforms.yml but only
# triggers deletion routines.
#
# Usage:
#   ansible-playbook playbooks/platform-delete.yml --tags delete --ask-vault-pass

- name: Delete Drupal platforms
  hosts: 
    - m01
    - m02
    - m03
    - r04
  become: true

  # Encrypted variables, like repository credentials, ...
  vars_files:
    - "../inventory/{{ env }}/group_vars/vaultvars.yml"

  tasks:
    - name: Drupal platform deletion
      include_role:
        name: project
      tags: 
        - delete
        - never  # Prevents accidental execution without explicit tags

  environment:
    COMPOSER_PROCESS_TIMEOUT: "1200"
    COMPOSER_MEMORY_LIMIT: "-1"
    COMPOSER_HOME: "/home/{{ ansible_user }}/.composer"
